// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1MsWx8OEr7qaCuBoC82vafk1SffjI5KI',
    appId: '1:718278353883:web:6dd36e3163614aae163dfe',
    messagingSenderId: '718278353883',
    projectId: 'mosaic-e24e2',
    authDomain: 'mosaic-e24e2.firebaseapp.com',
    storageBucket: 'mosaic-e24e2.firebasestorage.app',
    measurementId: 'G-WLGTDV9SG9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA02FgHWqE0d7YMdEyLBGsA6tfqiPFpfdo',
    appId: '1:718278353883:ios:a0fc69b2ddc1653b163dfe',
    messagingSenderId: '718278353883',
    projectId: 'mosaic-e24e2',
    storageBucket: 'mosaic-e24e2.firebasestorage.app',
    iosBundleId: 'com.example.mosaic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA02FgHWqE0d7YMdEyLBGsA6tfqiPFpfdo',
    appId: '1:718278353883:ios:a0fc69b2ddc1653b163dfe',
    messagingSenderId: '718278353883',
    projectId: 'mosaic-e24e2',
    storageBucket: 'mosaic-e24e2.firebasestorage.app',
    iosBundleId: 'com.example.mosaic',
  );

}